apiVersion: v1
kind: Service
metadata:
  name: platform-app
spec:
  selector:
    app: platform-app
  ports:
  - name: http
    port: 8081
    targetPort: 8080
  - name: grpc
    port: 9009
    targetPort: 9008
  type: ClusterIP